[logstreamer_cinder]
type = "LogstreamerInput"
log_directory = "/var/log/cinder"
file_match = '(?P<Service>.+)\.log\.?(?P<Seq>\d*)$'
differentiator = ['cinder','_','Service']
priority = ["^Index"]
decoder = "openstack"

[openstack]
type = "SandboxDecoder"
filename = "lua_modules/decoders/openstack.lua"
module_directory = "/usr/share/heka/lua_modules;/usr/share/heka/lua_modules/common"

